SELECT 
max(appointed_date) as appointed_data,
max(awards_1967_2017_2017_08_ID) as awards_1967_2017_2017_08_ID,
avg(birth_year) as birth_year,
MAX(current_age) as current_age,
ARRAY_AGG(current_rank IGNORE NULLS) as ranks_held,
MAX(current_star) as current_star,
MAX(current_status) as current_status,
ARRAY_AGG(current_unit IGNORE NULLS) as past_units,
first_name,
MAX(gender) as gender,
last_name,
MAX(middle_initial) as middle_initial,
MAX(org_hire_date) as org_hire_date,
MAX(race) as race,
MAX(resignation_date) as resignation_date,
MAX(resignation_year) as resignation_year,
MAX(star) as star,
MAX(start_date) as start_date,
ARRAY_AGG(unit_description IGNORE NULLS) as past_unit_descriptions,
MAX(unit_description) as unit_description,
MAX(complaint_category) as complaint_category,
MAX(complaint_code) as complaint_code,
MAX(cv) as cv,
MAX(final_finding) as final_finding,
MAX(final_outcome) as final_outcome,
MAX(recc_finding) as recc_finding,
max(recc_outcome) as recc_outcome
FROM `linear-stock-314817.invisinsitute_chicago_police_data.accused_updated` 
GROUP BY first_name, last_name, cr_id
